@startuml
title <size:36>Выбор</size>\n

actor "Богатырь" as b

:b: -left-> (Коня потеряешь)
:b: -right-> (Жизнь потеряешь)
:b: -up-> (Жив будешь, да себя позабудешь)
:b: -down-> (Отступление)
@enduml
