@startuml

actor "Кассир" as k 
participant "ClubPro" as cp

k -> cp: Запрос идентификации клиента по клубной карте
alt идентификация успешна
    cp -> k: идентификация успешна
else Отказ по причине отсутсвия связи
    group повторный запрос
        k -> cp: Отправка \nзапроса \nидентификации 
        loop 10 раз
            k -> cp: запрос идентификации 
        end
        k -> cp: Окончание отправки запросов
    end
else Другой тип отказа идентификации
    cp -> k: обратитесь в службу поддержки ошибка 100011
end alt

@enduml