@startuml
title 
Поиск 
//**золушки**//

Список кандидаток по позицию "Золушка"
|= №|= ФИО |= Комментарий |
| 1 | Дочь1 |  |
| 2 | Дочь2 |  |
| 3 | Падчерица |  |
end title

start

:Начало; 

repeat
    if (Девушка уже есть?) then (Да) 
        :Расстаться;
    else (нет)   
    endif
    :Встретить девушку;
    :Примерить ей туфельку;
repeat while (Подошла?) is (нет) 

:Золушка найдена;

stop
@enduml