'Предполагается реализовать следующий алгоритм для проставление ссылки на маршрут для ГП в новом Портале:
'
'	
'Выбираем все РО, связанные с ГП;
'	В выбранных РО определяем маршрут и сравниваем маршрут;
'	Проверяем, что у всех РО ссылка на один маршрут.
'	Если ссылка одна, то проставляем у ГП этот маршрут.
'	Если маршрутов в РО несколько, сравниваем точки маршрута (точку отгрузки, точку разгрузки и хаб) в маршруте в РО с теми значениями, что указано в ГП.
'	Если точки на маршруте РО и ГП совпали, тогда у ГП проставляем ссылку на этот маршрут
'	Если точки на маршруте РО и ГП не совпали, тогда смотрим наибольшее количество РО с одним маршрутом и проставляем маршрут этих РО. Если количество РО с разными маршрутами одинаково и ни одном из этих маршрутов точки не совпадает с указанными в ГП, тогда берем первый из маршрутов в РО.
@startuml

!procedure $DrawPP()
title Алгоритм для проставление ссылки на маршрут для ГП

state "<b>PO</b> по \n**ГП**" as SelectPO
state "Проверка маршрута" as CheckRoute
state "Проверка точек маршрута" as CheckPoint
state "Проставить маршрут у ГП" as SetRoute
state "Выбор маршрута" as SelectRoute

' надписи в узлах
SelectPO : Выбираем все РО, связанные с ГП
CheckRoute: В выбранных РО определяем маршрут
CheckPoint: Сравниваем точки маршрута 
CheckPoint: (точку отгрузки, точку разгрузки и хаб)
SelectRoute: ищем маршрут, который чаще всего повторяется

' связи
[*] --> SelectPO 

SelectPO --> CheckRoute

CheckRoute -->  SetRoute : У всех PO ссылка на один маршрут
CheckRoute -->  CheckPoint : Маршрутов в РО несколько
CheckPoint --> SetRoute : точки PO и ГП совпали
CheckPoint --> SelectRoute : разные точки 
SelectRoute --> SetRoute: ' есть "частый" маршрут
SelectRoute --> SetRoute: ' нет, выбираем первый

SetRoute --> [*] : Ok

' заметки
note left of SelectPO
  Примечание
  113333
end note
!endprocedure

@enduml